### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by Xiaozeeze** [xinghaochen/SLAB#4]
Could you please give me the link of the data set and the processing method of the data, and tell me which directory the data set should be placed in ?

**Comment by xinghaochen** [comment]
> Could you please give me the link of the data set and the processing method of the data, and tell me which directory the data set should be placed in ?

Which dataset do you mean?

**Comment by Xiaozeeze** [comment]
the dataset of Image Classification, ImageNet1k?

**Comment by xinghaochen** [comment]
You can download the ImageNet dataset via the [official website](https://www.image-net.org/download.php) and simply pass the path of your dataset using `--data-path <imagenet-path>` to start training.

```
python -m torch.distributed.launch --nproc_per_node=8 main.py --cfg <config-path> --data-path <imagenet-path> --output <output-path>
```

**Comment by Xiaozeeze** [comment]
Thank you very much, now I meet a new problem.

Traceback (most recent call last):
  File "eval.py", line 260, in <module>
    main()
  File "eval.py", line 136, in main
    module.merge_bn()
  File "/public/home/user/.conda/envs/SLAB/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PatchEmbed' object has no attribute 'merge_bn'

Do you know what happened? Do I need to add merge_bn to PatchEmbed?

**Comment by Xiaozeeze** [comment]
Thank you very much, now I meet a new problem.

Traceback (most recent call last):
File "eval.py", line 260, in
main()
File "eval.py", line 136, in main
module.merge_bn()
File "/public/home/user/.conda/envs/SLAB/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in getattr
raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PatchEmbed' object has no attribute 'merge_bn'

Do you know what happened? Do I need to add merge_bn to PatchEmbed?

**Comment by guojialong1** [comment]
Can you provide more detailed information to reproduce this error? Currently, we only support BN fusion for Swin Transformer. This error occurs if used for other models.
